language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

# command to install dependencies
install:
  - "pip install ."
  - "pip install -r test-requirements.txt"

# command to run tests
script: "flake8 setup.py cbox/ tests/ examples/ && py.test -s -v --junitxml=report.xml"

after_success:
  - codecov
